version: '2'

services:
  express-mongoose-es6-rest-api:
    build:
      context: .
    image: express-mongoose-es6-rest-api:latest

    volumes:
      - .:/app
      - /app/node_modules/
    env_file:
      - env/test.env
    links:
      - mongo
    command:
      - /bin/bash
      - -c
      - yarn --pure-lockfile && yarn test
  mongo:
    image: "mongo:3.6.3"
    ports:
      - "27017:27017"